- id: '1576512904840'
  alias: Lights:Dusk:Sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - entity_id: light.light_entry_2
    service: light.turn_on
  - entity_id: light.light_entry_1,light.light_entry_3
    service: light.turn_off
  - service: script.turn_on
    entity_id: script.1576603594014
    data: {}
  - delay: 00:45:00
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
  mode: single
- id: '1580492573046'
  alias: Switch:Adrian's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  - below: 35
    entity_id: sensor.nokia_5_3_battery_level
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_on
- id: '1580492681958'
  alias: Switch:Adrian's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: 80
    entity_id: sensor.nokia_5_3_battery_level
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.adrian_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_off
- id: '1580492785773'
  alias: Switch:Nancy's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: 85
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.nancy_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_off
- id: '1580492902537'
  alias: Switch:Nancy's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 03:30:00
    platform: time
  - below: 35
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_on
- id: '1581009244170'
  alias: Lights:Night:Time
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - entity_id: light.light_entry_3
    service: light.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_off
  - service: script.turn_on
    entity_id: script.1576604054568
    data: {}
  mode: single
- id: '1581407669990'
  alias: Phantom:Adrian
  description: ''
  trigger:
  - entity_id: person.adrian
    platform: state
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''person.adrian'')}}'
      topic: homeassistant/person/adrian
- id: '1582300595341'
  alias: Rollershutter:Dining:Day
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
  - service: light.turn_off
    entity_id: light.dining_room_lights, light.light_familyroom_1, light.music_room_light
    data: {}
- id: '1582300676427'
  alias: Rollershutter:Dining:Afternoon
  description: ''
  trigger:
  - at: '13:00:00'
    platform: time
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
- id: '1582646302706'
  alias: Rollershutter:Dining:Dusk
  description: ''
  trigger:
  - at: '15:00:00'
    platform: time
  - entity_id: group.family
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - after: '14:59:00'
    condition: time
  - condition: state
    entity_id: cover.dining_room_rollershutter
    state: close
  - before: sunset
    condition: sun
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
- id: '1584459956003'
  alias: Switch:Kettle:Started
  description: ''
  trigger:
  - entity_id: switch.switch_arlec_1
    for: 00:00:15
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.switch_arlec_1_energy_current
    state: '0.0'
  action:
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has not started.
      title: Kettle
  mode: single
- id: '1584460382480'
  alias: Switch:Kettle:Finished
  description: ''
  trigger:
  - below: 200
    entity_id: sensor.switch_arlec_1_energy_voltage
    platform: numeric_state
  condition:
  - condition: device
    device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    for:
      hours: 0
      minutes: 0
      seconds: 10
    type: is_on
  action:
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has boiled.
      title: Kettle
  - delay: 00:01:00
  - condition: state
    entity_id: binary_sensor.switch_arlec_1_button1
    state: 'on'
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has not been reset
      title: Kettle
  - device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    type: turn_off
  mode: single
- id: '1589216051030'
  alias: Switch:Boy's Heater:Off
  description: ''
  trigger:
  - at: 07:30:00
    platform: time
  condition: []
  action:
  - device_id: ebeeda6f09d4479bb461324e79f6f2a8
    domain: switch
    entity_id: switch.boy_s_heater
    type: turn_off
- id: '1589216101517'
  alias: Switch:Boy's Heater:On
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - device_id: ebeeda6f09d4479bb461324e79f6f2a8
    domain: switch
    entity_id: switch.boy_s_heater
    type: turn_on
- id: '1592566987204'
  alias: Light:Boys Bedroom:Off
  description: ''
  trigger:
  - device_id: 7b728c50558d4934a19c3f6078dba396
    domain: light
    entity_id: light.light_boys_bedroom
    platform: device
    type: turned_off
  condition: []
  action:
  - scene: scene.scene_boys_bedroom_off
- id: '1608395976316'
  alias: 'Switch:Boys-Fan: Temperature'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.temp_boys_bedroom_ds18b20_temperature
    below: '22'
    for: 00:05:00
  condition:
  - condition: state
    entity_id: switch.david_s_fan
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.jonathan_s_fan,switch.david_s_fan
  mode: single
