- id: '1576512904840'
  alias: Lights:Dusk:Sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - entity_id: light.light_entry_2
    service: light.turn_on
  - entity_id: light.light_entry_1,light.light_entry_3
    service: light.turn_off
  - service: script.turn_on
    entity_id: script.1576603594014
    data: {}
  - delay: 00:45:00
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
  mode: single
- id: '1580492573046'
  alias: Switch:Adrian's Phone Charger:Turn On
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  - platform: numeric_state
    entity_id: sensor.nokia_5_3_battery_level
    below: '35'
  - platform: state
    entity_id: switch.adrian_s_phone_charger
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.adrian_s_phone_charger
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.nokia_5_3_battery_level
      above: '95'
  - service: switch.turn_off
    entity_id: switch.adrian_s_phone_charger
  mode: restart
  max_exceeded: silent
- id: '1580492902537'
  alias: Switch:Nancy's Phone Charger:Turn On
  description: ''
  mode: single
  max_exceeded: silent
  trigger:
  - platform: time
    at: 03:30:00
  - platform: numeric_state
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    below: 35
  - platform: state
    entity_id: switch.nancy_s_phone_charger
    to: 'on'
  condition: []
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_on
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.nancy_s_g7_power_battery_sensor
      above: 80
  - service: switch.turn_off
    entity_id: switch.nancy_s_phone_charger
- id: '1581009244170'
  alias: Lights:Night:Time
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - entity_id: light.light_entry_3
    service: light.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_off
  - service: script.turn_on
    entity_id: script.1576604054568
    data: {}
  mode: single
- id: '1581407669990'
  alias: Phantom:Adrian
  description: ''
  trigger:
  - entity_id: person.adrian
    platform: state
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''person.adrian'')}}'
      topic: homeassistant/person/adrian
- id: '1582300595341'
  alias: Rollershutter:Dining:Day
  description: ''
  trigger:
  - event: sunrise
    platform: sun
    offset: '00:45:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.ble_temperature_a4c138b45222
      above: 22
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
  - service: light.turn_off
    entity_id: light.dining_room_lights, light.light_familyroom_1, light.music_room_light
    data: {}
- id: '1582300676427'
  alias: Rollershutter:Dining:Afternoon
  description: ''
  trigger:
  - at: '13:00:00'
    platform: time
  action:
  - entity_id: cover.dining_room_rollershutter
    service: >
      {% if states('sensor.ble_temperature_a4c138b45222') | float > 22 %}
        cover.close_cover
      {% else %}
        cover.open_cover
      {% endif %}
- id: '1582646302706'
  alias: Rollershutter:Dining:Dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
- id: '1584459956003'
  alias: Switch:Kettle:Started
  description: ''
  trigger:
  - entity_id: switch.switch_arlec_1
    for: '00:00:15'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.switch_arlec_1_energy_current
    state: '0.0'
  action:
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has not started.
      title: Kettle
  mode: single
- id: '1584460382480'
  alias: Switch:Kettle:Finished
  description: ''
  trigger:
  - below: 200
    entity_id: sensor.switch_arlec_1_energy_voltage
    platform: numeric_state
  condition:
  - condition: device
    device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    for:
      hours: 0
      minutes: 0
      seconds: 10
    type: is_on
  action:
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has boiled.
      title: Kettle
  - delay: 00:01:00
  - condition: state
    entity_id: binary_sensor.switch_arlec_1_button1
    state: 'on'
  - service: notify.mobile_app_adrian_s_phone
    data:
      message: The kettle has not been reset
      title: Kettle
  - device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    type: turn_off
  mode: single
- id: '1611676108901'
  alias: Lights:Master Bedroom:Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.temp_toggle
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.master_bedroom_lights
  mode: single
- id: '1611678447095'
  alias: Rollershutter:Jonathans Bedroom:Open:Time
  description: Open the Jonathans Bedroom Roller shutter at 07:30
  trigger:
  - platform: time
    at: 07:30:00
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: cover.set_cover_position
    data:
      position: 100
    target:
      entity_id: cover.boys_bedroom_rollershutter
  mode: single
- id: '1611763659185'
  alias: Rollershutter:Master Bedroom:Open:Time
  description: ''
  trigger:
  - platform: time
    at: '07:30:00'
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: cover.open_cover
    data: {}
    entity_id: cover.master_bedroom_rollershutter
  mode: single
- id: '1613410356423'
  alias: Rollershutters:Close:Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:45:00
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    entity_id: cover.master_bedroom_rollershutter, cover.boys_bedroom_rollershutter
  mode: single
