- id: '1575990406554'
  alias: Dining Room Light
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1153924'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - data:
      entity_id: light.dining_room_lights
    service: light.toggle
- id: '1576512904840'
  alias: Dining Room Lights Fade Up
  description: ''
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
    service: script.1576603594014
- id: '1576515032563'
  alias: Dining Room Lights Fade Down
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
    service: script.1576604054568
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - delay: 00:00:10
  - data:
      entity_id: script.1575907804253
    service: script.turn_on
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
