- id: '1575990406554'
  alias: Light:Dining Room:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712152'
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights_state
    service: input_boolean.turn_off
  - entity_id: light.dining_room_lights
    service_template: '{% if is_state(''light.dining_room_lights'', ''on'') %} light.turn_off
      {% else %} light.turn_on {% endif %}

      '
  - entity_id: light.lifx_d0_73_d5_38_46_87,light.lifx_d0_73_d5_38_15_d3,light.lifx_d0_73_d5_37_e4_e0,light.lifx_d0_73_d5_37_e5_cd
    data:
      brightness: 255
      color_name: white
    service: lifx.set_state
- id: '1576512904840'
  alias: Lights:Dusk:Sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: script.1576603594014
    service: script.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_on
  - entity_id: light.light_entry_1,light.light_entry_3
    service: light.turn_off
  - delay: 00:45:00
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
- id: '1576515032563'
  alias: Lights:Night:Timer
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - entity_id: script.1576604054568
    service: script.turn_on
  - entity_id: light.light_entry_1
    service: light.turn_on
  - entity_id: light.light_entry_3,light.light_entry_2
    service: light.turn_off
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - delay: 00:00:10
  - data:
      entity_id: script.1576604653358
    service: script.turn_on
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
- id: '1577291453719'
  alias: Light:Family Room Flood:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712146'
  condition: []
  action:
  - entity_id: light.light_familyroom_1
    service: light.toggle
- id: '1580492573046'
  alias: Switch:Adrian's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 06:00:00
    platform: time
  - below: '35'
    entity_id: sensor.adrian_s_g7_power_battery_sensor
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_on
- id: '1580492681958'
  alias: Switch:Adrian's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: '80'
    entity_id: sensor.adrian_s_g7_power_battery_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.adrian_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_off
- id: '1580492785773'
  alias: Switch:Nancy's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: '85'
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.nancy_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_off
- id: '1580492902537'
  alias: Switch:Nancy's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 05:30:00
    platform: time
  - below: '35'
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_on
- id: '1580657898955'
  alias: Light:Passage:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1945234'
  condition: []
  action:
  - entity_id: light.passage1,light.passage2
    service: light.toggle
- id: '1581009244170'
  alias: Lights:Night:Time
  description: ''
  trigger:
  - at: 00:21:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: script.1576604054568
    service: script.turn_on
  - entity_id: light.light_entry_3
    service: light.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_off
- id: '1581407669990'
  alias: Phantom:Adrian
  description: ''
  trigger:
  - entity_id: person.adrian
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states(''person.adrian'')}}'
      topic: homeassistant/person/adrian
    service: mqtt.publish
- id: '1582300595341'
  alias: Rollershutter:Dining:Day
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
  - data: {}
    entity_id: light.dining_room_lights, light.light_familyroom_1, light.light_musicroom_1
    service: light.turn_off
- id: '1582300676427'
  alias: Rollershutter:Dining:Afternoon
  description: ''
  trigger:
  - at: '13:00'
    platform: time
  condition:
  - above: '24'
    condition: numeric_state
    entity_id: sensor.bom_feels_like_c
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
- id: '1582646302706'
  alias: Rollershutter:Dining:Dusk
  description: ''
  trigger:
  - at: '15:00'
    platform: time
  - entity_id: group.family
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - after: '14:59'
    condition: time
  - condition: state
    entity_id: cover.dining_room_rollershutter
    state: close
  - before: sunset
    condition: sun
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
- id: '1582675757394'
  alias: Light:Dining Room:Rollershutters
  description: ''
  trigger:
  - entity_id: cover.dining_room_rollershutter
    platform: state
    to: open
  condition:
  - condition: and
    conditions:
    - before: sunset
      condition: sun
    - after: sunrise
      condition: sun
  action:
  - data: {}
    entity_id: light.dining_room_lights,light.light_musicroom_1
    service: light.turn_off
- id: '1582898443205'
  alias: Alert:Adrian's Phone:Button
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '9763496'
  - entity_id: sensor.rfb_button
    platform: state
    to: '9763476'
  - entity_id: sensor.rfb_button
    platform: state
    to: '9763474'
  - entity_id: sensor.rfb_button
    platform: state
    to: '9763473'
  condition: []
  action:
  - data:
      message: Boy's Help Button
    service: notify.mobile_app_adrian_s_g7_power
- id: '1584459956003'
  alias: Switch:Kettle:Started
  description: ''
  trigger:
  - entity_id: switch.switch_arlec_1
    for: 00:00:15
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.switch_arlec_1_energy_current
    state: '0.0'
  action:
  - data:
      message: The kettle has not started.
      title: Kettle
    service: notify.mobile_app_adrian_s_g7_power
- id: '1584460382480'
  alias: Switch:Kettle:Finished
  description: ''
  trigger:
  - below: '5'
    entity_id: sensor.switch_arlec_1_energy_current
    platform: numeric_state
  condition:
  - condition: device
    device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    type: is_on
  action:
  - data:
      message: The kettle has boiled.
      title: Kettle
    service: notify.mobile_app_adrian_s_g7_power
  - delay: 00:01:00
  - condition: state
    entity_id: binary_sensor.switch_arlec_1_button1
    state: 'on'
  - data:
      message: The kettle has not been reset
      title: Kettle
    service: notify.mobile_app_adrian_s_g7_power
  - device_id: 24270fe8bcce46d7a35d5929c4f467f0
    domain: switch
    entity_id: switch.switch_arlec_1
    type: turn_off
- id: '1584896652882'
  alias: Light:Family Room Flood:PIR:On
  description: ''
  trigger:
  - entity_id: binary_sensor.family_room
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - device_id: db1d35248fbf4a069418535ee7ebabcd
    domain: light
    entity_id: light.light_familyroom_1
    type: turn_on
- id: '1584897466331'
  alias: Light:Music Room:PIR:On
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '14330700'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - device_id: 336224c42a8e49f5b7e4bc18afdf8739
    domain: light
    entity_id: light.light_musicroom_1
    type: turn_on
  - data: {}
    entity_id: timer.light_music_room
    service: timer.start
- id: '1584898261946'
  alias: Light:Family Room Flood:PIR:Off
  description: ''
  trigger:
  - entity_id: binary_sensor.family_room
    for: 00:05:00
    platform: state
    to: 'off'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - device_id: db1d35248fbf4a069418535ee7ebabcd
    domain: light
    entity_id: light.light_familyroom_1
    type: turn_off
- id: '1584982860133'
  alias: Light:Music Room:PIR:Off
  description: ''
  trigger:
  - event_data:
      entity_id: timer.light_music_room
    event_type: timer.finished
    platform: event
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - device_id: 336224c42a8e49f5b7e4bc18afdf8739
    domain: light
    entity_id: light.light_musicroom_1
    type: turn_off
- id: '1584983332319'
  alias: Light:Back Passage:PIR:On
  description: ''
  trigger:
  - entity_id: binary_sensor.back_passage
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - data: {}
    entity_id: light.back_passage_lights
    service: light.turn_on
- id: '1584983557204'
  alias: Light:Back Passage:PIR:Off
  description: ''
  trigger:
  - entity_id: binary_sensor.back_passage
    for: 00:02:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.back_passage_lights
    service: light.turn_off
- id: '1585332194151'
  alias: Lights:Alfresco:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712148'
  condition: []
  action:
  - device_id: 1fa3e2fb09b748f8a3ba7c85a4d4bda2
    domain: light
    entity_id: light.light_alfresco_2
    type: toggle
