- id: '1576512904840'
  alias: Lights:Dusk:Sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - entity_id: light.light_entry_2
    service: light.turn_on
  - entity_id: light.light_entry_1,light.light_entry_3
    service: light.turn_off
  - service: script.turn_on
    entity_id: script.1576603594014
    data: {}
  - delay: 00:45:00
  - entity_id: cover.dining_room_rollershutter
    service: cover.close_cover
  mode: single
- id: '1580492573046'
  alias: Switch:Adrian's Phone Charger:Turn On
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  - platform: numeric_state
    entity_id: sensor.nokia_5_3_battery_level
    below: '35'
  - platform: state
    entity_id: switch.adrian_s_phone_charger
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.adrian_s_phone_charger
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.nokia_5_3_battery_level
      above: '95'
  - service: switch.turn_off
    entity_id: switch.adrian_s_phone_charger
  mode: restart
  max_exceeded: silent
- id: '1580492902537'
  alias: Switch:Nancy's Phone Charger:Turn On
  description: ''
  trigger:
  - platform: time
    at: 03:30:00
  - platform: numeric_state
    entity_id: sensor.nancys_phone_battery_level
    below: '35'
  - platform: state
    entity_id: switch.nancy_s_phone_charger
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_on
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.nancys_phone_battery_level
      above: '85'
  - service: switch.turn_off
    entity_id: switch.nancy_s_phone_charger
  mode: single
  max_exceeded: silent
- id: '1581009244170'
  alias: Lights:Night:Time
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.active
    state: 'on'
  action:
  - entity_id: light.light_entry_3
    service: light.turn_on
  - entity_id: light.light_entry_4
    service: light.turn_off
  mode: single
- id: '1581407669990'
  alias: Phantom:Adrian
  description: ''
  trigger:
  - entity_id: person.adrian
    platform: state
  condition:
  - condition: state
    entity_id: input_boolean.active
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''person.adrian'')}}'
      topic: homeassistant/person/adrian
- id: '1582300595341'
  alias: Rollershutter:Dining:Morning:Open
  description: ''
  trigger:
  - event: sunrise
    platform: sun
    offset: 00:45:00
  condition:
    - condition: numeric_state
      entity_id: sensor.ble_temperature_a4c138b45222
      above: 22
    - condition: numeric_state
      entity_id: sensor.darlington_rain_chance_0
      below: 50
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
  mode: single
- id: '1582300676427'
  alias: Rollershutter:Dining:Afternoon:Open
  description: ''
  trigger:
  - at: '13:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138b45222
    above: '22'
  - condition: numeric_state
    entity_id: sensor.darlington_rain_chance_0
    below: '50'
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138dfcf8d
    below: '24'
  action:
  - entity_id: cover.dining_room_rollershutter
    service: cover.open_cover
  mode: single
# - id: '1584459956003'
#   alias: Switch:Kettle:Started
#   description: ''
#   trigger:
#   - entity_id: switch.switch_arlec_1
#     for: 00:00:15
#     platform: state
#     to: 'on'
#   condition:
#   - condition: state
#     entity_id: binary_sensor.active
#     state: 'on'
#   - condition: state
#     entity_id: sensor.switch_arlec_1_energy_current
#     state: '0.0'
#   action:
#   - service: notify.mobile_app_adrian_s_phone
#     data:
#       message: The kettle has not started.
#       title: Kettle
#   mode: single
# - id: '1584460382480'
#   alias: Switch:Kettle:Finished
#   description: ''
#   trigger:
#   - below: 200
#     entity_id: sensor.switch_kettle_1_energy_voltage
#     platform: numeric_state
#   condition:
#   - condition: state
#     entity_id: binary_sensor.active
#     state: 'on'
#   - condition: device
#     device_id: 24270fe8bcce46d7a35d5929c4f467f0
#     domain: switch
#     entity_id: switch.switch_kettle_1
#     for:
#       hours: 0
#       minutes: 0
#       seconds: 10
#     type: is_on
#   action:
#   - service: notify.mobile_app_adrian_s_phone
#     data:
#       message: The kettle has boiled.
#       title: Kettle
#   - delay: 00:01:00
#   - condition: state
#     entity_id: binary_sensor.switch_kettle_1_button1
#     state: 'on'
#   - service: notify.mobile_app_adrian_s_phone
#     data:
#       message: The kettle has not been reset
#       title: Kettle
#   - device_id: 24270fe8bcce46d7a35d5929c4f467f0
#     domain: switch
#     entity_id: switch.switch_kettle_1
#     type: turn_off
#   mode: single
- id: '1611678447095'
  alias: Rollershutter:Jonathans Bedroom:Open:Time
  description: Open the Jonathans Bedroom Roller shutter at 07:30
  trigger:
  - platform: time
    at: 07:30:00
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138b45222
    above: '20'
  action:
  - service: cover.set_cover_position
    data:
      position: 100
    target:
      entity_id: cover.boys_bedroom_rollershutter
  mode: single
- id: '1611763659185'
  alias: Rollershutter:Master Bedroom:Open:Time
  description: ''
  trigger:
  - platform: time
    at: 07:30:00
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138fbfa2a
    above: '22'
  action:
  - service: cover.open_cover
    data: {}
    entity_id: cover.master_bedroom_rollershutter
  mode: single
- id: '1613410356423'
  alias: Rollershutters:Close:Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:45:00
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  action:
  - service: cover.close_cover
    data: {}
    entity_id: cover.master_bedroom_rollershutter, cover.boys_bedroom_rollershutter
  mode: single
- id: '1620144351328'
  alias: Switch:Nancys Electric Blanket
  description: ''
  trigger:
  - platform: state
    entity_id: person.nancy
    to: Home
  - platform: time
    at: '21:01:00'
    id: time
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  - condition: time
    after: '21:01:00'
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138fbfa2a
    below: '21'
  - condition: state
    entity_id: person.nancy
    state: Home
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.nancys_electric_blanket
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.nancys_electric_blanket
  mode: restart
- id: '1620211204748'
  alias: Climate:Boys Bedrooms:Warm
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: alarm_control_panel.mqtt_alarm
    state: disarmed
  - condition: state
    entity_id: group.family
    state: home
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138b45222
    below: '20'
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id:
      - climate.davids_thermostat
      - climate.jonathans_thermostat
  mode: single
- id: '1620211304299'
  alias: Turn off Boy's Bedroom Heaters / Fans
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id:
      - climate.davids_thermostat
      - climate.jonathans_thermostat
  mode: single
- id: '1620375343556'
  alias: Rollershutter:Dining:Afternoon:Close
  description: ''
  trigger:
  - platform: time
    at: '13:00:00'
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: numeric_state
    entity_id: sensor.ble_temperature_a4c138b45222
    below: '22'
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.darlington_rain_chance_0
      above: '50'
    - condition: numeric_state
      entity_id: sensor.ble_temperature_a4c138dfcf8d
      above: '24'
    - condition: sun
      before: sunset
      before_offset: 00:45:00
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.dining_room_rollershutter
  mode: single
- id: '1620376925668'
  alias: Light:DiningRoom:Off:Rollershutters:Open
  description: ''
  trigger:
  - platform: state
    entity_id: cover.dining_room_rollershutter
    to: open
  condition:
  - condition: state
    entity_id: input_boolean.active
    state: 'on'
  - condition: state
    entity_id: input_boolean.hot_water_system
    state: 'on'
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.dining_room_lights
      - light.family_room_lights
      - light.music_room_light
    data:
      transition: 30
  mode: single
- id: '1620377026335'
  alias: Light:DiningRoom:On:Rollershutters:Close
  description: ''
  trigger:
  - platform: state
    entity_id: cover.dining_room_rollershutter
    to: closed
  condition:
  - condition: state
    entity_id: binary_sensor.active
    state: 'on'
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: light.turn_on
    data:
      transition: 30
      color_temp: 280
      brightness: 100
  mode: single
- id: '1630777198910'
  alias: Switch:Jonathans Heater:Off
  description: Turn off Jonathan's Heater in the morning
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: state
    entity_id: input_boolean.active
    state: 'on'
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.jonathans_thermostat
  mode: single
- id: '1630909236404'
  alias: Lights:Toggle Study Lights:Button
  description: ''
  trigger:
  - platform: event
    event_type: esphome.rf_code_received
    event_data:
      code: '9763476'
  condition:
  - condition: state
    entity_id: input_boolean.active
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: scene.scene_study_bright
      sequence:
      - scene: scene.scene_study_normal
    default:
    - scene: scene.scene_study_bright
  mode: single
- id: '1636125125123'
  alias: Media:Boys-Speakers:Time
  description: Turn off the boy's speakers at midnight
  trigger:
  - platform: time
    at: 00:00
  action:
  - service: media_player.media_stop
    target:
      device_id:
      - fc5fc2c32960cd0c6d56f4ff0122a050
      - 5d1c01a08144d81793bda01ab075cae6
  mode: single
- id: '1654222877842'
  alias: TTS:Water-Heater:Sensor
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: person.adrian
    from: not_home
    platform: state
    to: home
  - entity_id: person.nancy
    from: not_home
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - alias: ''
    data:
      brightness: 255
      entity_id: light.welcome_lights
    service: light.turn_on
  - delay: 00:10:00
  - data:
      entity_id: light.welcome_lights
    service: light.turn_off
- id: '1570990825299'
  alias: Entry Light Off
  description: ''
  trigger:
  - entity_id: light.lifx_d0_73_d5_3e_87_c9
    for: '600'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 23c9569f55214533941f48beff102ceb
    domain: light
    entity_id: light.lifx_d0_73_d5_3e_87_c9
    type: turn_off
- id: '1571212561586'
  alias: Alarm Armed
  description: ''
  trigger:
  - entity_id: alarm_control_panel.mqtt_alarm
    platform: state
    to: triggered
  condition: []
  action:
  - data:
      message: Triggered at '{{ now() }}'
      title: Alarm
    service: notify.family
  - delay: 00:05:00
  - alias: ''
    data: {}
    service: alarm_control_panel.alarm_arm_away
- id: '1569866532936'
  alias: Arm Alarm
  trigger:
  - entity_id: group.family
    for: 00:02:00
    from: home
    platform: state
    to: not_home
  - entity_id: binary_sensor.arm_alarm
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.mqtt_alarm
    state: disarmed
  - condition: state
    entity_id: binary_sensor.front_door
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: alarm_control_panel.mqtt_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1570546741751'
  alias: Disarm Alarm
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.mqtt_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.mqtt_alarm
        state: pending
    - condition: state
      entity_id: group.family
      state: home
  action:
  - data:
      entity_id: alarm_control_panel.mqtt_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1570980280936'
  alias: Welcome Light
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: person.adrian
    from: not_home
    platform: state
    to: home
  - entity_id: person.nancy
    from: not_home
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - alias: ''
    data:
      brightness: 255
      entity_id: light.welcome_lights
    service: light.turn_on
  - delay: 00:10:00
  - data:
      entity_id: light.welcome_lights
    service: light.turn_off
- id: '1570990825299'
  alias: Entry Light Off
  description: ''
  trigger:
  - entity_id: light.lifx_d0_73_d5_3e_87_c9
    for: '600'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 23c9569f55214533941f48beff102ceb
    domain: light
    entity_id: light.lifx_d0_73_d5_3e_87_c9
    type: turn_off
- id: '1571212561586'
  alias: Alarm Armed
  description: ''
  trigger:
  - entity_id: alarm_control_panel.mqtt_alarm
    platform: state
    to: triggered
  condition: []
  action:
  - data:
      message: Triggered at '{{ now() }}'
      title: Alarm
    service: notify.family
  - delay: 00:05:00
  - alias: ''
    data: {}
    service: alarm_control_panel.alarm_arm_away
- id: '1569866532936'
  alias: Arm Alarm
  trigger:
  - entity_id: group.family
    for: 00:02:00
    from: home
    platform: state
    to: not_home
  - entity_id: binary_sensor.arm_alarm
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.mqtt_alarm
    state: disarmed
  - condition: state
    entity_id: binary_sensor.front_door
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: alarm_control_panel.mqtt_alarm
    service: alarm_control_panel.alarm_arm_away
- id: '1570546741751'
  alias: Disarm Alarm
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.mqtt_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.mqtt_alarm
        state: pending
    - condition: state
      entity_id: group.family
      state: home
  action:
  - data:
      entity_id: alarm_control_panel.mqtt_alarm
    service: alarm_control_panel.alarm_disarm
- id: '1570980280936'
  alias: Welcome Light
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: person.adrian
    from: not_home
    platform: state
    to: home
  - entity_id: person.nancy
    from: not_home
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  action:
  - alias: ''
    data:
      brightness: 255
      entity_id: light.welcome_lights
    service: light.turn_on
  - delay: 00:10:00
  - data:
      entity_id: light.welcome_lights
    service: light.turn_off
- id: '1570990825299'
  alias: Entry Light Off
  description: ''
  trigger:
  - entity_id: light.lifx_d0_73_d5_3e_87_c9
    for: '600'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 23c9569f55214533941f48beff102ceb
    domain: light
    entity_id: light.lifx_d0_73_d5_3e_87_c9
    type: turn_off
- id: '1571212561586'
  alias: Alarm Armed
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712152'
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - data: {}
    service: script.1576604653358
  - data:
      entity_id: light.dining_room_lights
    service: light.toggle
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_on
- id: '1576512904840'
  alias: Evening Lights
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - entity_id: light.entry_light_2
    service: light.turn_on
  - service: script.1576603594014
- id: '1576515032563'
  alias: Dining Room Lights Dim
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_38_46_87
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - alias: ''
    data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_38_15_d3
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_37_e4_e0
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - data:
      brightness: 15
      color_name: white
      entity_id: light.lifx_d0_73_d5_37_e4_e0
      transition: 900
    service: lifx.set_state
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - delay: 00:00:10
  - data:
      entity_id: script.1576604653358
    service: script.turn_on
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
- id: '1577291453719'
  alias: Family Room Flood Light
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712146'
  condition: []
  action:
  - entity_id: light.family_room_flood
    service: light.toggle
