- id: '1575990406554'
  alias: Dining Room Light
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1153924'
  condition: []
  action:
  - data:
      entity_id: light.dining_room_lights
    service: light.toggle
- id: '1576512904840'
  alias: Dining Room Lights Fade Up
  description: ''
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
    service: script.1576603594014
- id: '1576515032563'
  alias: Dining Room Lights Fade Down
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_37_e5_cd
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - data:
      entity_id: light.lifx_d0_73_d5_37_e5_cd
    service: light.turn_off
  - data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_37_e4_e0
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - data:
      entity_id: light.lifx_d0_73_d5_37_e4_e0
    service: light.turn_off
  - data:
      brightness: 0
      color_name: white
      entity_id: light.lifx_d0_73_d5_38_15_d3
      transition: 900
    service: lifx.set_state
  - delay: 00:15:00
  - data:
      entity_id: light.lifx_d0_73_d5_38_15_d3
    service: light.turn_off
  - data:
      brightness: 20
      color_name: white
      entity_id: light.lifx_d0_73_d5_38_46_87
      transition: 900
    service: lifx.set_state
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
