- id: '1575990406554'
  alias: Light:Dining Room:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712152'
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights_state
    service: input_boolean.turn_off
  - entity_id: light.dining_room_lights
    service_template: '{% if is_state(''light.dining_room_lights'', ''on'') %} light.turn_off
      {% else %} light.turn_on {% endif %}

      '
  - entity_id: light.lifx_d0_73_d5_38_46_87,light.lifx_d0_73_d5_38_15_d3,light.lifx_d0_73_d5_37_e4_e0,light.lifx_d0_73_d5_37_e5_cd
    data:
      brightness: 255
      color_name: white
    service: lifx.set_state
- id: '1576512904840'
  alias: Lights:Dusk:Sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:30:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: script.1576603594014
    service: script.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_on
  - entity_id: light.light_entry_1,light.light_entry_3
    service: light.turn_off
- id: '1576515032563'
  alias: Lights:Night:Timer
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
  - entity_id: script.1576604054568
    service: script.turn_on
  - entity_id: light.light_entry_1
    service: light.turn_on
  - entity_id: light.light_entry_3,light.light_entry_2
    service: light.turn_off
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - delay: 00:00:10
  - data:
      entity_id: script.1576604653358
    service: script.turn_on
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
- id: '1577291453719'
  alias: Light:Family Room Flood:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712146'
  condition: []
  action:
  - entity_id: light.light_familyroom_1
    service: light.toggle
- id: '1580492573046'
  alias: Switch:Adrian's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  - below: '35'
    entity_id: sensor.adrian_s_g7_power_battery_sensor
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_on
- id: '1580492681958'
  alias: Switch:Adrian's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: '80'
    entity_id: sensor.adrian_s_g7_power_battery_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.adrian_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.adrian_s_phone_charger
    service: switch.turn_off
- id: '1580492785773'
  alias: Switch:Nancy's Phone Charger:Turn Off
  description: ''
  trigger:
  - above: '85'
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.nancy_s_phone_charger
    state: 'on'
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_off
- id: '1580492902537'
  alias: Switch:Nancy's Phone Charger:Turn On
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  - below: '35'
    entity_id: sensor.nancy_s_g7_power_battery_sensor
    platform: numeric_state
  condition: []
  action:
  - entity_id: switch.nancy_s_phone_charger
    service: switch.turn_on
- id: '1580657898955'
  alias: Light:Passage:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1945234'
  condition: []
  action:
  - entity_id: light.passage1,light.passage2
    service: light.toggle
- id: '1580921810634'
  alias: Switch:Media Centre:Toggle
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '11532968'
  - entity_id: sensor.rfb_button
    platform: state
    to: '1944754'
  condition: []
  action:
  - entity_id: switch.media_centre
    service: switch.toggle
- id: '1581009244170'
  alias: Lights:Night:Time
  description: ''
  trigger:
  - at: 00:21:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: script.1576604054568
    service: script.turn_on
  - entity_id: light.light_entry_3
    service: light.turn_on
  - entity_id: light.light_entry_2
    service: light.turn_off
- id: '1581407669990'
  alias: Phantom:Adrian
  description: ''
  trigger:
  - entity_id: person.adrian
    platform: state
  condition: []
  action:
  - data:
      payload_template:
        '[object Object]':
      topic: homeassistant/person/adrian
    service: mqtt.publish
