- id: '1575990406554'
  alias: Dining Room Light
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712152'
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - data: {}
    service: script.1576604653358
  - data:
      entity_id: light.dining_room_lights
    service: light.toggle
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_on
- id: '1576512904840'
  alias: Evening Lights
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - entity_id: light.entry_light_2
    service: light.turn_on
  - service: script.1576603594014
- id: '1576515032563'
  alias: Dining Room Lights Fade Down
  description: ''
  trigger:
  - at: '20:30:00'
    platform: time
  condition: []
  action:
    service: script.1576604054568
- id: '1576515841194'
  alias: Dining Room Lights Off
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: input_boolean.christmas_lights
    service: input_boolean.turn_off
  - delay: 00:00:10
  - data:
      entity_id: script.1576604653358
    service: script.turn_on
  - data:
      entity_id: light.dining_room_lights
    service: light.turn_off
- id: '1577291453719'
  alias: Family Room Flood Light
  description: ''
  trigger:
  - entity_id: sensor.rfb_button
    platform: state
    to: '1712146'
  condition: []
  action:
  - entity_id: light.family_room_flood
    service: light.toggle
