---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: -31.923172
  longitude: 116.082237
  elevation: 149
  unit_system: metric
  time_zone: Australia/Perth
  name: Home

zone:
  name: home
  latitude: -31.923172
  longitude: 116.082237
  radius: 70

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://hass.na.id.au/
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.30.1
    - 2001:44b8:610b:3f30::1

logger:
  default: warning

config:

scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

frontend:
  themes: !include themes.yaml

discovery:
  ignore:
    - netgear_router

mqtt:
  broker: mqtt.na.id.au
  port: 1883
  username: hass
  password: !secret mqtt
  discovery: true
  discovery_prefix: homeassistant

google_assistant:
  project_id: hass
  service_account: !include hass-870815de073b.json
  report_state: true
  secure_devices_pin: !secret pin
  exposed_domains:
    - light
    - switch
    - alarm_control_panel
    - media_player
    - scene
  entity_config:
    group.all_automations:
      expose: false
    light.all_lights:
      expose: false
    light.master_bedroom_lights:
      expose: false
    light.lifx_d0_73_d5_37_e5_cd:
      expose: false
    light.lifx_d0_73_d5_37_e4_e0:
      expose: false
    light.lifx_d0_73_d5_38_15_d3:
      expose: false
    light.lifx_d0_73_d5_38_46_87:
      expose: false
    light.dinning_room_lights:
      expose: true
    light.welcome_lights:
      expose: false
    light.entry_lights:
      expose: false
    light.study:
      expose: false
    switch.adrian_s_phone_charger:
      expose: false
    switch.nancy_s_phone_charger:
      expose: false
    media_player.googlehome4026:
      expose: false
    media_player.glod:
      expose: false
    media_player.lias:
      expose: false
    media_player.cliff:
      expose: false
    media_player.kitchen_speaker:
      expose: false
    script.1575907804253:
      expose: true
    script.1575974067886:
      expose: true
    vacuum.sammy:
      expose: 'true'
      google_assistant_type: 'switch’

notify:
  - name: a_xmpp
    platform: xmpp
    sender: home@na.id.au
    password: !secret xmpp
    recipient: a@na.id.au
  - platform: html5
    name: Push
    vapid_pub_key:
      !secret vapid_pub
    vapid_prv_key:
      !secret vapid_prv
    vapid_email:
      Adrian.a.Woodley@gmail.com
  - name: family
    platform: group
    services:
      - service: mobile_app_adrians_phone
      - service: mobile_app_nancy_s_phone
      - service: a_xmpp

alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code_arm_required: false
    code_disarm_required: false

binary_sensor:
  - platform: mqtt
    state_topic: "home/alarm/zones/0"
    name: "Front Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/alarm/zones/5"
    name: "Laundry/Garage Door"
    device_class: door
  - platform: rpi_gpio
    invert_logic: true
    pull_mode: UP
    ports:
      27: Arm Alarm
      22: Doorbell
      23: Bedroom Light

sensor:
  - platform: mqtt
    state_topic: "home/OpenMQTTGateway_SRFB/SRFBtoMQTT"
    name: 'RFB Button'
    value_template: '{{value_json.value}}'
    qos: 1
    expire_after: 1


input_boolean:
  christmas_lights_state:
    name: Running state of the Christmas light pattern
    initial: off
# States:
# 0 - Christmas Lights Disabled
# 1 - Christmas Lights Running
    
light: !include lights.yaml

vacuum: !include vacuum.yaml

media_player:
  - platform: yamaha
    name: Yamaha Receiver
    host: 192.168.30.32
    source_ignore:
      - "AUX"
      - "Radio"
      - "HDMI3"
      - "HDMI4"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "TUNER"
      - "NET RADIO"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      HDMI1: "Blu-Ray"
      HDMI2: "ChromeCast"

