---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: -31.923172
  longitude: 116.082237
  elevation: 149
  unit_system: metric
  time_zone: Australia/Perth
  name: !secret name
  external_url: https://hass.na.id.au
  internal_url: !secret internal_url
  media_dirs:
    local: /Media

zone:
  name: home
  latitude: -31.923172
  longitude: 116.082237
  radius: 70

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.30.1
    - 127.0.0.1
    - 2001:44b8:610b:3f30::1

logger:
  default: warning
#  logs:
#    homeassistant.components.tasmota: debug

config:

recorder:
  purge_keep_days: 5
  db_url: !secret postgresql
  exclude:
    entities:
      - binary_sensor.back_passage
      - binary_sensor.family_room
      - binary_sensor.laundry_garage_door
      - binary_sensor.light_media_3
      - binary_sensor.media_room
      - binary_sensor.study

#zeroconf:
#  default_interface: true

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
timer: !include timer.yaml

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include themes.yaml

discovery:
  ignore:
    - netgear_router

mqtt:
  broker: localhost
  port: 1883
  username: hass
  password: !secret mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'home/hass/active'
    payload: 'OFFLINE'
    retain: false
    qos: 0
  will_message:
    topic: 'home/hass/active'
    payload: 'OFFLINE'
    retain: false
    qos: 0


device_tracker:
  - platform: mqtt
    devices:
      adrian_keys: 'blecker/efa03eac2b0f'
      adrian_vivosmart_4: 'blecker/d7be10bbfaf5'
      adrian_instinct: 'blecker/dab46862ceea'
      nancy_charge: 'blecker/e3eb8b55b045'
      guest: 'location/guest'
    payload_home: 'present'
    payload_not_home: 'not_present'
    source_type: bluetooth_le


lifx:
  light:
    - broadcast: 192.168.29.51 # Dining-1
    - broadcast: 192.168.29.52 # Dining-2
    - broadcast: 192.168.29.53 # Dining-3
    - broadcast: 192.168.29.54 # Dining-4
    - broadcast: 192.168.29.55 # Boys-Bedroom-1
    - broadcast: 192.168.29.56 # Study-1
    - broadcast: 192.168.29.57 # Passage-1
    - broadcast: 192.168.29.58 # Passage-2
    - broadcast: 192.168.29.59 # Entrance-1
    - broadcast: 192.168.29.60 # Play-Room-1
    - broadcast: 192.168.29.61 # Music-Room-1
    - broadcast: 192.168.29.62 # Family-Room-Flood
    - broadcast: 192.168.29.63 # Family-Room-Stand
    - broadcast: 192.168.29.64 # Study-4

google_assistant:
  project_id: hass
  service_account: !include hass-870815de073b.json
  report_state: !secret google_report_state
  secure_devices_pin: !secret pin
  expose_by_default: false
  entity_config:
    light.back_passage_lights:
      expose: true
    light.dining_room_lights:
      expose: true
    light.entry_lights:
      expose: true
    light.alfresco_light_1:
      expose: true
    light.light_alfresco_2:
      expose: true
    light.light_backverandah_1:
      expose: true
    light.light_bedside_1:
      expose: true
    light.light_bedside_2:
      expose: true
    light.light_jonathans_bedroom:
      expose: true
    light.light_davids_bedroom:
      expose: true
    light.light_christmas_1:
      expose: true
    light.light_familyroom_1:
      expose: true
    light.lifx_familyroom_stand:
      expose: true
    light.light_masterbedroom_1:
      expose: true
    light.light_media_1:
      expose: true
    # light.light_media_2:
    #   expose: true
    light.light_media_3:
      expose: true
    light.music_room_light:
      expose: true
    switch.switch_kettle:
      expose: true
    switch.fireplace_fan:
      expose: true
    switch.tv:
      expose: true
    switch.media_centre:
      expose: true
    switch.boy_s_heater:
      expose: true
    switch.nancys_electric_blanket:
      expose: true
    input_boolean.party_lights:
      expose: true
      name: 'Party Lights'
    input_boolean.christmas_lights:
      expose: true
      name: 'Christmas Lights'
    input_boolean.guest:
      expose: true
      name: 'Guest'
    script.1575974067886:
      expose: true
      name: 'Enough Christmas'
    scene.1592309890640:
      expose: true
      name: 'Red Lights'
    vacuum.sammy:
      expose: true
    cover.dining_room_rollershutter:
      expose: true
    cover.master_bedroom_rollershutter:
      expose: true
    cover.jonathans_bedroom_rollershutter:
      expose: true
    # sensor.temp_jonathans_bedroom_ds18b20_temperature:
    #   expose: true
    cover.davids_bedroom_rollershutter:
      expose: true
    sensor.ble_temperature_a4c138fbfa2a :
      expose: true
      name: 'Master Bedroom Temperature'
    sensor.ble_temperature_a4c13887d585 :
      expose: true
      name: 'Diningroom Temperature'
    sensor.rollershutter_diningroom_ds18b20_temperature:
      expose: true
      name: 'Study Temperature'
    climate.jonathans_thermostat:
      expose: true
    climate.davids_thermostat:
      expose: true
    alarm_control_panel.mqtt_alarm:
      expose: true


# calendar:
#   - platform: caldav
#     url: "https://calendar.google.com/calendar/ical/rd12cc9q5lpepgi9ob36pu5k94%40group.calendar.google.com/public/basic.ics"




notify:
  - platform: html5
    name: Push
    vapid_pub_key:
      !secret vapid_pub
    vapid_prv_key:
      !secret vapid_prv
    vapid_email:
      Adrian.a.Woodley@gmail.com
  - name: family
    platform: group
    services:
      - service: mobile_app_adrians_phone
      - service: mobile_app_nancy_s_phone


tplink:
  discovery: true
  switch:
    - host: 192.168.29.71
    - host: 192.168.29.72
    - host: 192.168.29.73
    - host: 192.168.29.74
    - host: 192.168.29.76 # Radios
  strip:
    - host: 192.168.29.75


alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code_arm_required: false
    code_disarm_required: false


climate:
  - platform: dualmode_generic
    unique_id: climate.jonathans_thermostat
    name: Jonathans Thermostat
    heater: switch.jonathans_heater
    cooler: switch.jonathans_fan
    target_sensor: sensor.temp_jonathans_bedroom_ds18b20_temperature
    target_temp: 22
    min_cycle_duration: '00:05:00'
    initial_hvac_mode: 'off'
  # - platform: generic_thermostat
  #   unique_id: climate.jonathans_fan
  #   name: Jonathans Fan
  #   heater: switch.jonathans_fan
  #   target_sensor: sensor.temp_jonathans_bedroom_ds18b20_temperature
  #   target_temp: 22
  #   min_cycle_duration: '00:05:00'
  #   initial_hvac_mode: 'off'
  #   ac_mode: true
  - platform: dualmode_generic
    unique_id: climate.davids_thermostat
    name: Davids Thermostat
    heater: switch.davids_heater
    cooler: switch.davids_fan
    target_sensor: sensor.temp_davids_bedroom_ds18b20_temperature
    target_temp: 22
    min_cycle_duration: '00:05:00'
    initial_hvac_mode: 'off'
  # - platform: generic_thermostat
  #   unique_id: climate.davids_fan
  #   name: Davids Fan
  #   heater: switch.davids_fan
  #   target_sensor: sensor.temp_davids_bedroom_ds18b20_temperature
  #   target_temp: 22
  #   min_cycle_duration: '00:05:00'
  #   initial_hvac_mode: 'off'
  #   ac_mode: true

binary_sensor:
  - platform: mqtt
    state_topic: "home/alarm/zones/0"
    name: "Front Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/alarm/zones/1"
    name: "Media Room"
    device_class: motion
  - platform: mqtt
    state_topic: "home/alarm/zones/2"
    name: "Family Room"
    device_class: motion
  - platform: mqtt
    state_topic: "home/alarm/zones/3"
    name: "Back Passage"
    device_class: motion
  - platform: mqtt
    state_topic: "home/alarm/zones/4"
    name: "Study"
    device_class: motion
  - platform: mqtt
    state_topic: "home/alarm/zones/5"
    name: "Laundry/Garage Door"
    device_class: door
  - platform: template
    sensors:
      active:
        friendly_name: "Active IP"
        value_template: "{{ states('sensor.partner') == states('sensor.local_ip') or is_state('sensor.partner', 'OFFLINE') or is_state('sensor.partner', 'unavailable') }}"

sensor:
  - platform: time_date
    display_options:
    - 'time'
    - 'date'
    - 'time_date'
  - platform: min_max
    name: 'Average Indoor Temperature'
    type: mean
    entity_ids:
      - sensor.rollershutter_diningroom_ds18b20_temperature
      - sensor.temp_jonathans_bedroom_ds18b20_temperature
      - sensor.temp_davids_bedroom_ds18b20_temperature
      - sensor.ble_temperature_a4c138dfcf8d # Dining Room
      - sensor.ble_temperature_a4c13887d585 # Living Room
      - sensor.ble_temperature_a4c138fbfa2a # Master Bedroom
      - sensor.ble_temperature_a4c138fbfa2a # Sewing Room
  - platform: mqtt
    state_topic: "home/+/SRFBtoMQTT"
    name: 'RFB Button'
    value_template: '{{value_json.value}}'
    qos: 1
    expire_after: 1
  - platform: mqtt
    state_topic: "tele/tasmota/IR/+/RESULT"
    name: 'IR Button'
    value_template: "{{value_json.IrReceived.Data}}"
    qos: 1
    expire_after: 1
  - platform: mqtt
    state_topic: "tele/tasmota/IR/+/RESULT"
    name: "IR Last"
    value_template: "{{value_json.IrReceived.Data}}"
    qos: 1
  - platform: mqtt
    state_topic: "home/hass/active"
    name: partner
    expire_after: 65


switch:
  - platform: mqtt
    name: Sammy
    command_topic: "cmnd/tasmotas/irsend"
    payload_on: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818100FF\",\"DataLSB\":\"0x818100FF\",\"Repeat\":0}"
  - platform: mqtt
    state_topic: "home/hass/active"
    command_topic: "home/hass/active"
    name: Active
    # payload_on: "{{ states('sensor.local_ip') }}"
    payload_off: "OFFLINE"
    value_template: "{{ states('sensor.local_ip') == value}}"
  - platform: mqtt
    name: TV
    icon: mdi:television
    optimistic: false
    command_topic: "cmnd/tasmotas/irsend"
    payload_on: "{\"Protocol\":\"PANASONIC\",\"Bits\":48,\"Data\":\"0x40040100BCBD\",\"DataLSB\":\"0x022080003DBD\",\"Repeat\":0}"
    payload_off: "{\"Protocol\":\"PANASONIC\",\"Bits\":48,\"Data\":\"0x40040100BCBD\",\"DataLSB\":\"0x022080003DBD\",\"Repeat\":0}"
  - platform: flux
    lights:
      - light.light_familyroom_1
      - light.light_musicroom_1
      - light.light_study_1
      - light.back_passage_lights
      - light.dining_room_lights
    name: Fluxer
    start_time: '7:00'
    stop_time: '20:00'
    start_colortemp: 6500
    sunset_colortemp: 3030
    stop_colortemp: 2000
    disable_brightness_adjust: true
    mode: mired


cover:
  # - platform: mqtt
  #   name: "Dining Room Rollershutter"
  #   command_topic: cmnd/tasmotas/4A78A8/BACKLOG
  #   payload_open: "ShutterOpen1 1"
  #   payload_close: "ShutterClose1 1"
  #   payload_stop: "Power3 1"
  - platform: mqtt
    name: "Master Bedroom Rollershutter"
    unique_id: "D8BFC01A3A5F"
    state_topic: "shellies/shellyswitch25-D8BFC01A3A5F/roller/0"
    command_topic: "shellies/shellyswitch25-D8BFC01A3A5F/roller/0/command"
    position_topic: "shellies/shellyswitch25-D8BFC01A3A5F/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-D8BFC01A3A5F/roller/0/command/pos"
    payload_available: "true"
    payload_not_available: "false"
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    state_stopped: "stop"
    position_open: 100
    position_closed: 0
    qos: 1
    retain: false
    optimistic: false
  - platform: mqtt
    unique_id: "40F5200467D0"
    name: "Jonathans Bedroom Rollershutter"
    state_topic: "shellies/shellyswitch25-40F5200467D0/roller/0"
    command_topic: "shellies/shellyswitch25-40F5200467D0/roller/0/command"
    position_topic: "shellies/shellyswitch25-40F5200467D0/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-40F5200467D0/roller/0/command/pos"
    payload_available: "true"
    payload_not_available: "false"
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    state_stopped: "stop"
    position_open: 100
    position_closed: 0
    qos: 1
    retain: false
    optimistic: false
  - platform: mqtt
    unique_id: "40F520055224"
    name: "Davids Bedroom Rollershutter"
    state_topic: "shellies/shellyswitch25-40F520055224/roller/0"
    command_topic: "shellies/shellyswitch25-40F520055224/roller/0/command"
    position_topic: "shellies/shellyswitch25-40F520055224/roller/0/pos"
    set_position_topic: "shellies/shellyswitch25-40F520055224/roller/0/command/pos"
    payload_available: "true"
    payload_not_available: "false"
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    state_stopped: "stop"
    position_open: 100
    position_closed: 0
    qos: 1
    retain: false
    optimistic: false


input_select:
  study_scene:
    name: Currently Active Scene for Study
    options:
      - unknown
      - scene.scene_study_off
      - scene.scene_study_normal
      - scene.scene_study_bright
    initial: unknown

light: !include lights.yaml

vacuum: !include vacuum.yaml

media_player:
  - platform: mpd
    host: 192.168.30.10
    name: DeathOfRats
  - platform: dlna_dmr
    name: Cliff
    url: http://192.168.30.35/dd.xml
    # - platform: yamaha # takes too long to restart if yamaha off
    #   name: Yamaha Receiver
    #   host: 192.168.30.32
    #   source_ignore:
    #     - "AUX"
    #     - "Radio"
    #     - "HDMI3"
    #     - "HDMI4"
    #     - "AV1"
    #     - "AV2"
    #     - "AV3"
    #     - "AV4"
    #     - "AV5"
    #     - "AV6"
    #     - "TUNER"
    #     - "NET RADIO"
    #     - "USB"
    #     - "V-AUX"
    #     - "iPod (USB)"
    #   source_names:
    #     HDMI1: "Blu-Ray"
    #     HDMI2: "ChromeCast"

# panasonic_viera: # didn't work with this model TV
#   host: 192.168.30.31
#   name: Panasonic TV
#   turn_on_action:
#     - service: mqtt.publish
#       data:
#         topic: "cmnd/tasmotas/irsend"
#         payload: "{\"Protocol\":\"PANASONIC\",\"Bits\":48,\"Data\":\"0x40040100BCBD\",\"DataLSB\":\"0x022080003DBD\",\"Repeat\":0}"
