---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: -31.923172
  longitude: 116.082237
  elevation: 149
  unit_system: metric
  time_zone: Australia/Perth
  name: Home

zone:
  name: home
  latitude: -31.923172
  longitude: 116.082237
  radius: 70

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://hass.na.id.au/
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.30.1
    - 2001:44b8:610b:3f30::1

logger:
  default: warning

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

frontend:
  themes: !include themes.yaml

discovery:
  ignore:
    - netgear_router

mqtt:
  broker: mqtt.na.id.au
  port: 1883
  username: hass
  password: ***REMOVED***
  discovery: true
  discovery_prefix: homeassistant

google_assistant:
  project_id: hass
  service_account: !include hass-870815de073b.json
  report_state: true
#  api_key: ***REMOVED***
  secure_devices_pin: ***REMOVED***
  exposed_domains:
    - light
    - switch
    - alarm_control_panel
    - media_player
    - scene
  entity_config:
    group.all_automations:
      expose: false
    light.all_lights:
      expose: false
    light.master_bedroom_lights:
      expose: false
    light.lifx_d0_73_d5_37_e5_cd:
      expose: false
    light.lifx_d0_73_d5_37_e4_e0:
      expose: false
    light.lifx_d0_73_d5_38_15_d3:
      expose: false
    light.lifx_d0_73_d5_38_46_87:
      expose: false
    light.dinning_room_lights:
      expose: true
    light.welcome_lights:
      expose: false
    light.entry_lights:
      expose: false
    media_player.googlehome4026:
      expose: false
    media_player.kitchen_speaker:
      expose: false
    script.1575907804253:
      expose: true
    script.1575974067886:
      expose: true

notify:
  - name: a_xmpp
    platform: xmpp
    sender: home@na.id.au
    password: ***REMOVED***
    recipient: a@na.id.au
  - platform: html5
    name: Push
    vapid_pub_key:
      ***REMOVED***
    vapid_prv_key:
      ***REMOVED***
    vapid_email:
      Adrian.a.Woodley@gmail.com
  - name: family
    platform: group
    services:
      - service: mobile_app_adrians_phone
      - service: mobile_app_nancy_s_phone
      - service: a_xmpp

alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code_arm_required: false
    code_disarm_required: false

binary_sensor:
  - platform: mqtt
    state_topic: "home/alarm/zones/0"
    name: "Front Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/alarm/zones/5"
    name: "Laundry/Garage Door"
    device_class: door
  - platform: rpi_gpio
    invert_logic: true
    pull_mode: UP
    ports:
      27: Arm Alarm
      22: Doorbell
      23: Bedroom Light

sensor:
  - platform: mqtt
    state_topic: "home/OpenMQTTGateway_SRFB/SRFBtoMQTT"
    name: 'RFB Button'
    value_template: '{{value_json.value}}'
    qos: 1
    expire_after: 1


input_boolean:
  christmas_lights:
    name: Keep Christmas light pattern running
    
light:
  - platform: mqtt
    name: "Master Bedroom"
    state_topic: "home/lights/stat/arlec1/POWER"
    command_topic: "home/lights/cmnd/arlec1/POWER"
    availability_topic: "home/lights/tele/arlec1/LWT"
    brightness_state_topic: "home/lights/stat/arlec1/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec1/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec1/CT"
    color_temp_state_topic: "home/lights/stat/arlec1/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Music Room"
    state_topic: "home/lights/stat/arlec2/POWER"
    command_topic: "home/lights/cmnd/arlec2/POWER"
    availability_topic: "home/lights/tele/arlec2/LWT"
    brightness_state_topic: "home/lights/stat/arlec2/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec2/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec2/CT"
    color_temp_state_topic: "home/lights/stat/arlec2/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Media Room Light Stand"
    state_topic: "home/lights/stat/arlec3/POWER"
    command_topic: "home/lights/cmnd/arlec3/POWER"
    availability_topic: "home/lights/tele/arlec3/LWT"
    brightness_state_topic: "home/lights/stat/arlec3/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec3/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec3/CT"
    color_temp_state_topic: "home/lights/stat/arlec3/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Adrian's Bedside Table"
    state_topic: "home/lights/stat/arlec4/POWER"
    command_topic: "home/lights/cmnd/arlec4/POWER"
    availability_topic: "home/lights/tele/arlec4/LWT"
    brightness_state_topic: "home/lights/stat/arlec4/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec4/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec4/CT"
    color_temp_state_topic: "home/lights/stat/arlec4/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Nancy's Bedside Table"
    state_topic: "home/lights/stat/arlec5/POWER"
    command_topic: "home/lights/cmnd/arlec5/POWER"
    availability_topic: "home/lights/tele/arlec5/LWT"
    brightness_state_topic: "home/lights/stat/arlec5/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec5/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec5/CT"
    color_temp_state_topic: "home/lights/stat/arlec5/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Study"
    state_topic: "home/lights/stat/arlec6/POWER"
    command_topic: "home/lights/cmnd/arlec6/POWER"
    availability_topic: "home/lights/tele/arlec6/LWT"
    brightness_state_topic: "home/lights/stat/arlec6/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec6/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec6/CT"
    color_temp_state_topic: "home/lights/stat/arlec6/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Media Room Reading Light"
    state_topic: "home/lights/stat/arlec7/POWER"
    command_topic: "home/lights/cmnd/arlec7/POWER"
    availability_topic: "home/lights/tele/arlec7/LWT"
    brightness_state_topic: "home/lights/stat/arlec7/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec7/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Christmas Tree Lights"
    state_topic: "home/lights/stat/arlec8/POWER"
    command_topic: "home/lights/cmnd/arlec8/POWER"
    availability_topic: "home/lights/tele/arlec8/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Family Room Flood"
    state_topic: "home/lights/stat/arlec9/POWER"
    command_topic: "home/lights/cmnd/arlec9/POWER"
    availability_topic: "home/lights/tele/arlec9/LWT"
    brightness_state_topic: "home/lights/stat/arlec9/RESULT"
    brightness_command_topic: "home/lights/cmnd/arlec9/Dimmer"
    brightness_scale: 100
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "home/lights/cmnd/arlec9/CT"
    color_temp_state_topic: "home/lights/stat/arlec9/RESULT"
    color_temp_value_template: "{{value_json.CT}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Alfresco Light"
    state_topic: "home/lights/stat/arlec10/POWER"
    command_topic: "home/lights/cmnd/arlec10/POWER"
    availability_topic: "home/lights/tele/arlec10/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entry Light 1"
    state_topic: "home/lights/stat/arlec11/POWER"
    command_topic: "home/lights/cmnd/arlec11/POWER"
    availability_topic: "home/lights/tele/arlec11/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entry Light 2"
    state_topic: "home/lights/stat/arlec12/POWER"
    command_topic: "home/lights/cmnd/arlec12/POWER"
    availability_topic: "home/lights/tele/arlec12/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Entry Light 3"
    state_topic: "home/lights/stat/arlec13/POWER"
    command_topic: "home/lights/cmnd/arlec13/POWER"
    availability_topic: "home/lights/tele/arlec13/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: group
    name: Media Room Lights
    entities:
      - light.media_room_light_stand
      - light.media_room_reading_light
  - platform: group
    name: Master Bedroom Lights
    entities:
      - light.master_bedroom
      - light.adrian_s_bedside_table
      - light.nancy_s_bedside_table
  - platform: group
    name: Welcome Lights
    entities: 
      - light.lifx_d0_73_d5_3e_87_c9
      - light.entry_light_1
      - light.entry_light_2
      - light.entry_light_3
  - platform: group
    name: Dining Room Lights
    entities:
      - light.lifx_d0_73_d5_38_46_87
      - light.lifx_d0_73_d5_38_15_d3
      - light.lifx_d0_73_d5_37_e4_e0
      - light.lifx_d0_73_d5_37_e5_cd
  - platform: group
    name: Entry Lights
    entities:
      - light.entry_light_1
      - light.entry_light_2
      - light.entry_light_3


# device_tracker:
#  - platform: ubus
#    scan_interval: 60
#    consider_home: 120
#    host: 192.168.30.251
#    username: root
#    password: ***REMOVED***
#    dhcp_software: dnsmasq
#    new_device_defaults:
#      track_new_devices: false
#  - platform: ping
#    scan_interval: 60
#    consider_home: 120
#    hosts:
#      Adrians_Moto_G5s: 192.168.30.27
#      Nancys_Moto_G5s: 192.168.30.26
#  - platform: netgear_macs
#    scan_interval: 60
#    consider_home: 120
#    host: 192.168.30.250
#    username: admin
#    password: ***REMOVED***
#    new_device_defaults:
#      track_new_devices: false

media_player:
  - platform: yamaha
    name: Yamaha Receiver
    source_ignore:
      - "AUX"
      - "Radio"
      - "HDMI3"
      - "HDMI4"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "TUNER"
      - "NET RADIO"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      HDMI1: "Blu-Ray"
      HDMI2: "ChromeCast"
#  - platform: dlna_dmr
#    url: http://192.168.30.35/dd.xml
#    name: Cliff
