
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
    latitude: -31.923172
    longitude: 116.082237
    elevation: 149
    unit_system: metric
    time_zone: Australia/Perth
    name: Home

zone:
    name: home
    latitude: -31.923172
    longitude: 116.082237
    radius: 70

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    base_url: https://hass.na.id.au/
    use_x_forwarded_for: true
    trusted_proxies:
            - 192.168.30.1
            - 2001:44b8:610b:3f30::1

logger:
  default: warning

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

frontend:
  themes: !include themes.yaml

discovery:
  ignore:
    - netgear_router

mqtt:
  broker: mqtt.na.id.au
  port: 1883
  username: hass
  password: !secret mqtt
  discovery: true
  discovery_prefix: homeassistant

google_assistant:
  project_id: hass
  service_account: !include hass-870815de073b.json
  report_state: true
  secure_devices_pin: !secret pin
  exposed_domains:
    - light
    - switch
    - alarm_control_panel
    - media_player
    - scene
  entity_config:
    group.all_automations:
      expose: false
    light.all_lights:
      expose: false
    light.master_bedroom_lights:
      expose: false
    light.lifx_d0_73_d5_37_e5_cd:
      expose: false
    light.lifx_d0_73_d5_37_e4_e0:
      expose: false
    light.lifx_d0_73_d5_38_15_d3:
      expose: false
    light.lifx_d0_73_d5_38_46_87:
      expose: false
    light.dinning_room_lights:
      expose: true
    media_player.googlehome4026:
      expose: false
    media_player.kitchen_speaker:
      expose: false
    script.1575907804253:
      expose: true
    script.1575974067886:
      expose: true

notify:
  - name: a_xmpp
    platform: xmpp
    sender: home@na.id.au
    password: !secret xmpp
    recipient: a@na.id.au
  - platform: html5
    name: Push
    vapid_pub_key: ***REMOVED***
    vapid_prv_key: ***REMOVED***
    vapid_email: Adrian.a.Woodley@gmail.com
  - name: family
    platform: group
    services:
      - service: mobile_app_adrians_phone
      - service: mobile_app_nancy_s_phone
      - service: a_xmpp

alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code_arm_required: false
    code_disarm_required: false

binary_sensor:
  - platform: mqtt
    state_topic: "home/alarm/zones/0"
    name: "Front Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/alarm/zones/5"
    name: "Laundry/Garage Door"
    device_class: door
  - platform: rpi_gpio
    invert_logic: true
    pull_mode: UP
    ports:
      27: Arm Alarm
      22: Doorbell
      23: Bedroom Light

sensor:
  - platform: mqtt
    state_topic: "home/OpenMQTTGateway_SRFB/SRFBtoMQTT"
    name: 'RFB Button'
    value_template: '{{value_json.value}}'
    qos: 1
    expire_after: 1


light: !include lights.yaml


#lifx:
#  light:
#    - broadcast: 192.168.29.51 # Dining-1
#    - broadcast: 192.168.29.52 # Dining-2
#    - broadcast: 192.168.29.53 # Dining-3
#    - broadcast: 192.168.29.54 # Dining-4
#    - broadcast: 192.168.29.55 # Jonathans-1
#    - broadcast: 192.168.29.56 # Study-1
#    - broadcast: 192.168.29.57 # Media Room Light Stand
#    - broadcast: 192.168.29.58 # Master Bedroom
#    - broadcast: 192.168.29.59 # Entrance-1
#    - broadcast: 192.168.29.60 # Davids-1
#    - broadcast: 192.168.29.61 # Music-Room-1
#    - broadcast: 192.168.29.62 # Family-Room-Flood
#    - broadcast: 192.168.29.63 # Family-Room-Stand
#    - broadcast: 192.168.29.66 # Kitchen-1
#    - broadcast: 192.168.29.67 # Kitchen-2
#    - broadcast: 192.168.29.68 # Passage-1
#    - broadcast: 192.168.29.69 # Passage-2


climate:
  - platform: dualmode_generic
    unique_id: climate.jonathans_thermostat
    name: Jonathans Thermostat
    heater: switch.jonathans_thermostat
    cooler: switch.jonathans_thermostat
    target_sensor: sensor.jonathans_bedroom_temperature
    target_temp: 21
    min_cycle_duration: '00:05:00'
    initial_hvac_mode: 'off'
  - platform: dualmode_generic
    unique_id: climate.davids_thermostat
    name: Davids Thermostat
    heater: switch.davids_thermostat
    cooler: switch.davids_thermostat
    target_sensor: sensor.davids_thermostat_temperature
    target_temp: 21
    min_cycle_duration: '00:05:00'
    initial_hvac_mode: 'off'


template:
  - binary_sensor:
    - name: 'Washing Machine Running'
      unique_id: binary_sensor.washing_machine_running
      state: >
        {{ states('sensor.washing_machine_current')|float(0) > 120 }}
      delay_off:
        minutes: 5
      icon: mdi:washing-machine
  - trigger:
    - platform: event
      event_type: esphome.rf_code_received
      event_data:
        code: '44556'
      id: "off"
    - platform: state
      entity_id:
      - binary_sensor.washing_machine_running
      from: "off"
      to: "on"
      id: "on"
    binary_sensor:
    - name: 'Washing Machine Full'
      unique_id: binary_sensor.washing_machine_full
      state: "{{ trigger.id }}"
  - binary_sensor:
    - name: 'Clothes Dryer'
      unique_id: binary_sensor.clothes_dryer
      state: >
        {{ states('sensor.clothes_dryer_current')|float(0) > 0 }}
      delay_off:
        minutes: 2
      icon: mdi:tumble-dryer
  - binary_sensor:
    - name: 'DishWasher'
      unique_id: binary_sensor.dishwasher
      state: >
        {{ states('sensor.dishwasher_current')|float(0) > 0 }}
      delay_off:
        minutes: 2
      icon: mdi:dishwasher
  # - binary_sensor:
  #   - name: 'TV'
  #     unique_id: binary_sensor.tv
  #     state: >
  #       {{ states('sensor.media_centre_current')|float(0) > 650 }}
  #     icon: mdi:television
  - binary_sensor:
    - name: 'Water Heater'
      unique_id: binary_sensor.water_heater
      state: >
        {{ states('sensor.water_heater_power')|float(0) > 0 }}
      icon: mdi:water-boiler
  - binary_sensor:
    - name: "Active"
      unique_id: binary_sensor.active
      state: "{{ states('sensor.partner') == states('sensor.local_ip') or is_state('sensor.partner', 'offline') or is_state('sensor.partner', 'unavailable') }}"
  - binary_sensor:
    - name: "Bathroom Light"
      unique_id: binary_sensor.light_bathroom_1
      state: "{{states('sun.sun') == 'below_horizon' and states('sensor.bathroom_shelly_luminosity') > '150'}}"
  - binary_sensor:
    - name: "Bin Day"
      unique_id: binary_sensor.bin_day
      state: >-
        {{
          (
            (
              states('sensor.recycling_days') == '8' or 
              states('sensor.recycling_days') == '1'
            )
            and is_state('device_tracker.radbeacon_g_b62e', 'home')
          )
        or
          (
            is_state('device_tracker.radbeacon_g_b62e', 'not_home')
            and not(
              states('sensor.recycling_days') == '8' or 
              states('sensor.recycling_days') == '1'
            )
          )
        }}
  - binary_sensor:
    - name: "Recycling Day"
      unique_id: binary_sensor.recycling_day
      state:  >-
        {{
          (
            (
              states('sensor.recycling_days') == '1'
            )
            and is_state('device_tracker.radbeacon_g_ba2a', 'home')
          )
        or
          (
            is_state('device_tracker.radbeacon_g_ba2a', 'not_home')
            and not(
              states('sensor.recycling_days') == '1'
            )
          )
        }}
  - binary_sensor:
    - name: 'Open House'
      unique_id: binary_sensor.open_house
      state: >-
        {{
        (states('sensor.indoor_temperature_average') < states('input_number.house_target_temperature') and
        states('sensor.outside_temperature') > states('sensor.indoor_temperature_average'))
        or
        (states('sensor.indoor_temperature_average') > states('input_number.house_target_temperature') and
        states('sensor.outside_temperature') < states('sensor.indoor_temperature_average'))
        }}
  - sensor:
    - name: 'Electricity Total'
      unique_id: sensor.electricity_total
      state: "{{ ((states('sensor.shelly_em3_1_channel_a_power')|float(0) + states('sensor.shelly_em3_1_channel_b_power')|float(0) + states('sensor.shelly_em3_1_channel_c_power')|float(0))|round(2))}}"
      unit_of_measurement: W
  - sensor:
    - name: 'Cost Total'
      unique_id: sensor.electricity_cost_total
      state: "{{ ((states('sensor.shelly_em3_1_channel_a_energy_cost')|float(0) + states('sensor.shelly_em3_1_channel_b_energy_cost')|float(0) + states('sensor.shelly_em3_1_channel_c_energy_cost')|float(0))|round(2))}}"
      unit_of_measurement: AUD
  - sensor:
    - name: 'Energy Sum'
      unique_id: sensor.energy_sum
      state: "{{ (states('sensor.shelly_em3_1_channel_a_energy')|float(0) + states('sensor.shelly_em3_1_channel_b_energy')|float(0) + states('sensor.shelly_em3_1_channel_c_energy')|float(0))|round(2)}}"
      unit_of_measurement: kWh
  - sensor:
    - name: 'Energy Cost per Hour'
      unique_id: sensor.energy_cost_per_hour
      state: "{{ (states('sensor.electricity_total')|float(0) / 1000 * 0.266612) | round(2) }}"
      unit_of_measurement: AUD
  # - sensor:
  #   - name: 'Unaccounted Power'
  #     unique_id: sensor.unaccounted_power
  #     state: >-
  #       {% set total = (states('sensor.electricity_total')|float(0)) %}
  #       {%  set accounted = (
  #           states('sensor.servers_power')|float(0) +
  #           states('sensor.media_centre_power')|float(0) + 
  #           states('sensor.fridge_power')|float(0) + 
  #           states('sensor.dishwasher_power')|float(0) + 
  #           states('sensor.clothes_dryer_power')|float(0) + 
  #           states('sensor.boys_pcs_power')|float(0) + 
  #           states('sensor.pc_power')|float(0) + 
  #           states('sensor.kettle_power')|float(0) + 
  #           states('sensor.master_bedroom_airconditioner_power')|float(0) +
  #           states('sensor.network_power')|float(0) +
  #           states('sensor.radios_current_consumption')|float(0) +
  #           states('sensor.servers_power')|float(0) +
  #           states('sensor.washing_machine_power')|float(0) +
  #           states('sensor.davids_heater_power')|float(0) +
  #           states('sensor.jonathans_heater_power')|float(0) +
  #           states('sensor.nancys_blanket_power')|float(0) +
  #           states('sensor.fireplace_fan_power')|float(0) +
  #           states('sensor.water_heater_power')|float(0) +
  #           states('sensor.monitors_current_consumption')|float(0)
  #           ) %}
  #       {%  set unaccounted = (total - accounted)|round(2) %}
  #       {%  if unaccounted <= 0 %}
  #           0
  #       {%  else %}
  #           {{ unaccounted }}
  #       {%  endif %}
  #     unit_of_measurement: W
  - sensor:
    - name: 'Oven'
      unique_id: sensor.oven
      state: >-
        {% set current = states('sensor.shelly_em3_1_channel_a_current')|float(0) %}
        {% if current > 9 and current < 11 %}
          Heating
        {% elif current > 0.2 and current < 0.3 %}
          At Temperature
        {% else %}
          off
        {% endif %}


switch:
  - platform: template
    switches:
      tv:
        friendly_name: 'TV'
        unique_id: switch.tv
        value_template: "{{ states('sensor.media_centre_current')|float(0) > 200 }}"
        turn_on:
          service: button.press
          target:
            entity_id: button.panasonic_tv_power
        turn_off:
          service: button.press
          target:
            entity_id: button.panasonic_tv_power
  - platform: wake_on_lan
    mac: 6c:0b:84:e2:f6:19
    name: Jonathans Computer
    host: conina
    turn_off:
      service: shell_command.turn_off_jonathans_computer
  - platform: wake_on_lan
    mac: FC:4D:D4:3F:7C:FB
    name: Davids Computer
    host: nijel
    turn_off:
      service: shell_command.turn_off_davids_computer
  - platform: wake_on_lan
    mac: 6C:0B:84:E2:8C:42
    name: Hex
    host: Hex
    turn_off:
      service: shell_command.suspend_hex
  - platform: wake_on_lan
    mac: c8:d3:ff:a6:7a:f2
    name: Ponder
    host: Ponder
    turn_off:
      service: shell_command.suspend_ponder
  # - platform: wake_on_lan
  #   mac: C8:CB:B8:05:5E:6F
  #   name: Ruby
  #   host: Ruby
  #   turn_off:
  #     service: script.ruby_suspend


utility_meter:
  energy_total:
    unique_id: sensor.energy_total
    source: sensor.energy_sum
    cycle: daily
  energy_cost:
    unique_id: sensor.energy_cost
    source: sensor.cost_total
    cycle: daily


sensor:
  - platform: time_date
    display_options:
    - 'time'
    - 'date'
    - 'time_date'
  - platform: min_max
    name: 'Average Indoor Temperature'
    type: mean
    entity_ids:
      - sensor.rollershutter_diningroom_ds18b20_temperature
      - sensor.jonathans_bedroom_temperature
      - sensor.davids_bedroom_temperature
      - sensor.temperature_fe01191a0ae4e128 # Family Room
      - sensor.temperature_843c01d60760f228 # Media Room
      - sensor.ble_temperature_a4c138dfcf8d # Dining Room
      - sensor.ble_temperature_a4c13887d585 # Music Room
      - sensor.ble_temperature_a4c1387f98b8 # Sewing Room
  - platform: integration
    method: left
    source: sensor.servers_power # PC191HA (bf012dac0c9cee209dvmjj)
    name: 'Servers'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.media_centre_power # PC191HA (bf0a25ce6f7c8aab61vwq2)
    name: 'Media Centre'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.fridge_power # PC191HA (bf17f32c06256d34efjpmo)
    name: 'Fridge'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.dishwasher_power # PC191HA (bf3396d64e6ddf40dbhrzw)
    name: 'Dish Washer'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.clothes_dryer_power # PC191HA (bf4515197da95eb2fbnnt1)
    name: 'Clothes Dryer'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.boys_pcs_power # PC191HA (bf81eb45e0bb24485dizc5)
    name: 'Boys PC'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.pc_power # PC191HA (bf88d927aab4af56e7jblh)
    name: 'PC'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.kettle_power # PC191HA (bfbb5c3a70eabdace6hewr)
    name: 'Kettle'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.master_bedroom_airconditioner_power # PC191HA (bfbe5b22167c47577f9dvj)
    name: 'Master Bedroom Air-Conditioner'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.network_power # PC191HA (bfcd8aea86ab6e5135r33d)
    name: 'Network'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.lego_light_power # PC191HA (bfe5d7cd1a780671dcvxfl)
    name: 'Lego Light'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.washing_machine_power # PC191HA (bffefd23341d564551zzg5)
    name: 'Washing Machine'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.davids_thermostat_power # PCTH01HA (bf150fc48d778cd4782sja)
    name: 'Davids Heater'
    # unit_prefix: k
    round: 2
  - platform: integration
    method: left
    source: sensor.jonathans_thermostat_power # PCTH01HA (bf70af88eb3f29e429dj1x)
    name: 'Jonathans Heater'
    # unit_prefix: k
    round: 2
  # - platform: integration
  #   method: left
  #   source: sensor.unaccounted_power
  #   name: 'Unaccounted'
  #   # unit_prefix: k
  #   round: 2

media_player:
  - platform: yamaha
    name: Yamaha Receiver
    source_ignore:
      - "AUX"
      - "Radio"
      - "HDMI3"
      - "HDMI4"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "TUNER"
      - "NET RADIO"
      - "USB"
      - "V-AUX"
      - "iPod (USB)"
    source_names:
      HDMI1: "Blu-Ray"
      HDMI2: "ChromeCast"

