---
aliases: !include aliases.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: -31.923172
  longitude: 116.082237
  elevation: 149
  unit_system: metric
  time_zone: Australia/Perth
  name: *name

zone:
  name: home
  latitude: -31.923172
  longitude: 116.082237
  radius: 70

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://hass.na.id.au/
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.30.1
    - 2001:44b8:610b:3f30::1

logger:
  default: warning

config:

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include themes.yaml

discovery:
  ignore:
    - netgear_router

mqtt:
  broker: localhost
  port: 1883
  username: hass
  password: !secret mqtt
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'home/hass/leonard'
    payload: 'online'
    retain: 'false'
  will_message:
    topic: 'home/hass/leonard'
    payload: 'offline'
    retain: 'false'

google_assistant:
  project_id: hass
  service_account: !include hass-870815de073b.json
  report_state: *google_report_state
  secure_devices_pin: !secret pin
  expose_by_default: false
  entity_config:
    light.light_bedside_1:
      expose: true
    light.light_bedside_2:
      expose: true
    light.light_familyroom_1:
      expose: true
    light.light_masterbedroom_1:
      expose: true
    light.light_media_1:
      expose: true
    light.light_media_2:
      expose: true
    light.light_musicroom_1:
      expose: true
    light.dinning_room_lights:
      expose: true
    light.entry_lights:
      expose: true
    light.lifx_mini_5386a2:
      expose: true
    light.lifx_d0_73_d5_3e_87_c9:
      expose: true
    switch.media_centre:
      expose: true
    script.1575907804253:
      expose: true
    script.1575974067886:
      expose: true
    vacuum.sammy:
      expose: true
    cover.dining_room_rollershutter:
      expose: true

calendar:
  - platform: caldav
    url: https://calendar.google.com/calendar/ical/rd12cc9q5lpepgi9ob36pu5k94%40group.calendar.google.com/public/basic.ics


notify:
  - name: a_xmpp
    platform: xmpp
    sender: home@na.id.au
    password: !secret xmpp
    recipient: a@na.id.au
  - platform: html5
    name: Push
    vapid_pub_key:
      !secret vapid_pub
    vapid_prv_key:
      !secret vapid_prv
    vapid_email:
      Adrian.a.Woodley@gmail.com
  - name: family
    platform: group
    services:
      - service: mobile_app_adrians_phone
      - service: mobile_app_nancy_s_phone
      - service: a_xmpp

alarm_control_panel:
  - platform: mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code_arm_required: false
    code_disarm_required: false

binary_sensor:
  - platform: mqtt
    state_topic: "home/alarm/zones/0"
    name: "Front Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/alarm/zones/5"
    name: "Laundry/Garage Door"
    device_class: door
  - platform: mqtt
    state_topic: "home/hass/johnson"
    device_class: connectivity
    payload_on: "online"
    payload_off: "offline"
  # - platform: rpi_gpio
  #   invert_logic: true
  #   pull_mode: UP
  #   ports:
  #     27: Arm Alarm
  #     22: Doorbell
  #     23: Bedroom Light

sensor:
  - platform: mqtt
    state_topic: "home/+/SRFBtoMQTT"
    name: 'RFB Button'
    value_template: '{{value_json.value}}'
    qos: 1
    expire_after: 1
  - platform: mqtt
    state_topic: "tele/tasmota/+/RESULT"
    name: 'IR Button'
    value_template: '{{value_json.IrReceived}}'
    qos: 1
    expire_after: 1


switch:
  - platform: mqtt
    name: Sammy
    command_topic: "tasmotas/cmnd/irsend"
    payload_on: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818100FF\",\"DataLSB\":\"0x818100FF\",\"Repeat\":0}"


cover:
  - platform: mqtt
    name: "Dining Room Rollershutter"
    command_topic: tasmota/4A78A8/cmnd/BACKLOG
    payload_open: "Power1 on"
    payload_stop: "Power2 on"
    payload_close: "Power3 on"


input_boolean:
  christmas_lights_state:
    name: Running state of the Christmas light pattern
    initial: off
# States:
# 0 - Christmas Lights Disabled
# 1 - Christmas Lights Running
    
light: !include lights.yaml

vacuum: !include vacuum.yaml

# media_player:
#   - platform: yamaha
#     name: Yamaha Receiver
#     host: 192.168.30.32
#     source_ignore:
#       - "AUX"
#       - "Radio"
#       - "HDMI3"
#       - "HDMI4"
#       - "AV1"
#       - "AV2"
#       - "AV3"
#       - "AV4"
#       - "AV5"
#       - "AV6"
#       - "TUNER"
#       - "NET RADIO"
#       - "USB"
#       - "V-AUX"
#       - "iPod (USB)"
#     source_names:
#       HDMI1: "Blu-Ray"
#       HDMI2: "ChromeCast"

