---
- platform: group
  name: Media Room Lights
  entities:
    - light.light_media_1
    - light.light_media_2
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.light_masterbedroom_1
    - light.light_bedside_1
    - light.light_bedside_2
- platform: group
  name: Welcome Lights
  entities: 
    - light.lifx_d0_73_d5_3e_87_c9
    - light.light_entry_1
    - light.light_entry_2
    - light.light_entry_3
- platform: group
  name: Dining Room Lights
  entities:
    - light.lifx_d0_73_d5_38_46_87
    - light.lifx_d0_73_d5_38_15_d3
    - light.lifx_d0_73_d5_37_e4_e0
    - light.lifx_d0_73_d5_37_e5_cd
- platform: group
  name: Entry Lights
  entities:
    - light.light_entry_1
    - light.light_entry_2
    - light.light_entry_3
- platform: group
  name: Back Passage Lights
  entities:
    - light.passage1
    - light.passage2