---
- platform: group
  name: Media Room Lights
  entities:
    - light.light_media_1
    - light.light_media_2
    - light.light_media_3
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.light_masterbedroom_1
    - light.light_bedside_1
    - light.light_bedside_2
- platform: group
  name: Welcome Lights
  entities: 
    - light.lifx_front_door
    - light.light_entry_1
    - light.light_entry_2
    - light.light_entry_3
- platform: group
  name: Dining Room Lights
  entities:
    - light.lifx_dining_room_1
    - light.lifx_dining_room_2
    - light.lifx_dining_room_3
    - light.lifx_dining_room_4
- platform: group
  name: Entry Lights
  entities:
    - light.light_entry_1
    - light.light_entry_2
    - light.light_entry_3
- platform: group
  name: Passage Lights
  entities:
    - light.lifx_passage_1
    - light.lifx_passage_2
- platform: group
  name: Family Room Lights
  entities:
    - light.lifx_familyroom_stand
    - light.light_familyroom_1
- platform: group
  name: Study Lights
  entities:
    - light.lifx_study_1
    - light.light_study_2
    - light.light_study_3
