- platform: mqtt
  name: "Sammy"
  schema: state
  supported_features:
    # - turn_on
    # - turn_off
    - return_home
    - start
    - pause
    - stop
  command_topic: "sonoffs/cmnd/irsend"
  # payload_turn_on: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818100FF\",\"DataLSB\":\"0x818100FF\",\"Repeat\":0}"
  # payload_turn_off: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818100FF\",\"DataLSB\":\"0x818100FF\",\"Repeat\":0}"
  payload_return_to_base: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x8181807F\",\"DataLSB\":\"0x818101FE\",\"Repeat\":0}"
  payload_start: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818110EF\",\"DataLSB\":\"0x818108F7\",\"Repeat\":0}"
  payload_pause: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818110EF\",\"DataLSB\":\"0x818108F7\",\"Repeat\":0}"
  payload_stop: "{\"Protocol\":\"SAMSUNG\",\"Bits\":32,\"Data\":\"0x818110EF\",\"DataLSB\":\"0x818108F7\",\"Repeat\":0}"