blueprint:
  name: Light Brightness Step
  description: 'Step the brightness at night time'
  domain: automation
  input:
    button_id:
      name: Button ID
      description: ID of the RF button to use as a trigger
      selector:
        text:
    light_id:
      name: Target Light
      description: Light to toggle
      selector:
        entity:
          domain: light

trigger:
  - platform: event
    event_type: esphome.rf_code_received
    event_data:
      code: !input button_id

condition:
- condition: state
  entity_id: input_boolean.active
  state: 'on'

action:
  - choose:
      - conditions:
          - condition: time
            after: '21:00'
            before: '07:00'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light_id
                    state: 'on'
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input light_id
              - conditions:
                  - condition: state
                    entity_id: !input light_id
                    state: 'on'
                sequence:
                  - service: light.turn_on
                    data:
                      color_temp: 250
                      brightness: 255
                    target:
                      entity_id: !input light_id          
            default:
              - service: light.turn_on
                data:
                  color_temp: 370
                  brightness: 15
                target:
                  entity_id: !input light_id
    default:
      - service: light.toggle
        data:
          color_temp: 250
          brightness: 255
        target:
          entity_id: !input light_id