blueprint:
  name: Light Cover Morning
  description: 'Fade up light or open cover in morning'
  domain: automation
  input:
    light_id:
      name: Light ID
      description: ID of the light to control
      selector:
        entity:
          domain: light
    cover_id:
      name: Roller Shutter ID
      description: Roller shutter to control
      default: {}
      selector:
        entity:
          domain: cover
    schedule_id:
      name: Schedule ID
      description: Schedule to determine wake up time
      default: {}
      selector:
        entity:
          domain: schedule
    temperature_threshold:
      name: Temperature Threshold
      description: Temperature below which the light will turn on, rather than the cover open.
      default: 20
      selector:
        number:
          min: 0
          max: 40
          step: 1
          mode: slider
          unit_of_measurement: celsius
    temperature_sensor_id:
      name: Temperature Sensor
      description: Temperature sensor to monitor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    person_id:
      name: Person ID
      description: This person must be home for automation to trigger
      default: {}
      selector:
        entity:
          domain: person

trigger:
  - platform: state
    entity_id: !input schedule_id
    to: "on"

condition:
  - condition: state
    entity_id: !input person_id
    state: 'home'
  - condition: state
    entity_id: input_boolean.active
    state: 'on'

action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: !input temperature_sensor_id
        below: !input temperature_threshold
      sequence:
        - service: light.turn_on
          data:
            transition: 300
            color_temp: 320
            brightness: 255
          target:
            entity_id: !input light_id
    default:
      - service: cover.open_cover
        data: {}
        entity_id: !input cover_id
