blueprint:
  name: Thermostat Door Trigger
  description: 'Toggle thermostat based on door open/close'
  domain: automation
  input:
    door_id:
      name: Door ID
      description: ID of the triggering door sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: door
    light_id:
      name: Target Thermostat
      description: Thermostat to toggle
      selector:
        entity:
          domain: thermostat
    temperature_id:
      name: Monitor Temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature_value:
      name: Threshold Temperature
      description: Temperature below which thermostate will be enabled.
      selector:
    
trigger:
  - platform: state
    entity_id: !input door_id

condition:
  - condition: time
    after: '21:00:00'
    before: '08:00:00'
  - condition: state
    entity_id: input_boolean.active
    state: 'on'

action:
  - choose:
    - conditions:
      - condition: state
        entity_id: !input door_id
        state: "off"
      - condition: numeric_state
        entity_id: !input temperature_id
        below: below
        above: above
        entity_id: !input light_id
        state: "on"
      - condition: numeric_state
        entity_id: !input light_id
        attribute: brightness
        below: 255
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input light_id
    - conditions:
      - condition: state
        entity_id: !input door_id
        state: "on"
      - condition: state
        entity_id: !input light_id
        state: "off"
      sequence:
      - service: light.turn_on
        target:
          entity_id: !input light_id
        data:
          color_temp: 250
          brightness: 252
